<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Hydride</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <ApplicationManifest>..\app.manifest</ApplicationManifest>

    <!-- 图标 -->
    <ApplicationIcon>..\misc\Proj.ico</ApplicationIcon>

    <!-- 输出 exe 名称 -->
    <AssemblyName>hydride_svc64</AssemblyName>

    <!-- 版本号 -->
    <Version>1.3.0</Version>

    <!-- 程序集元数据 -->
    <Company>NXRKYMANE SOFTWARE</Company>
    <Product>Hydride System Memory Manager Service</Product>
    <Description>Windows system memory management service</Description>
    <Copyright>Copyright (C) $([System.DateTime]::Now.Year) NXRKYMANE SOFTWARE</Copyright>
    <NeutralLanguage>en</NeutralLanguage>

    <DebugType>none</DebugType>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <!-- 发布设置 -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <PublishDir>$(MSBuildThisFileDirectory)publish\</PublishDir>
  </PropertyGroup>

  <Target Name="PublishAfterBuild" AfterTargets="Build">
    <Exec Command="dotnet publish &quot;$(MSBuildThisFileDirectory)Hydride.csproj&quot; -c $(Configuration) -r win-x64 --no-build --no-restore" />
  </Target>

</Project>
